matrix-org/node-irc

package.json

Ref PR: https://github.com/martynsmith/node-irc/pull/386

Get the actual hostname from a whois call

---

docs/API.rst
lib/irc.js

Add localPort connection option to specify socket bind port when

---

lib/irc.js

This provides the ability to know what messages would be sent in light of a potentially large text being sent by an IRC client.
This is required for PR https://github.com/matrix-org/matrix-appservice-irc/pull/118

Client.wouldSend method for large message checking

---

lib/irc.js

Fixes https://github.com/matrix-org/matrix-appservice-irc/issues/185

Case map incoming PRIVMSG and NOTICEs

---

lib/irc.js

Every known command which has a channel arg should now be casemapped correctly.

Case map all the things

---

lib/irc.js

Also don't silently swallow unknown usermode errors!

Add setUserMode to set a user's modes

---

lib/irc.js

https://github.com/matrix-org/matrix-appservice-irc/issues/352

Fix matrix-org/matrix-appservice-irc#352

---

lib/irc.js
package.json

Merging in some relevant PRs from upstream as per #19 
Includes:
+ martynsmith#487
+ martynsmith#396
+ martynsmith#397
+ martynsmith#443

Pull bug fixes from upstream

---

.travis.yml
lib/irc.js

Ensure we have channel data before removing it.

---

src/capabilities.ts
src/codes.ts
src/irc.ts

Depends upon #61 
This basically revamps how we do capabilities by splitting some of the code into a caps object. I'm not entirely convinced that we've gone far enough given there is a lot of logic in `irc.ts` still though.
As a side effect, I've also added support for the SASL codes in https://ircv3.net/registry

Improve capabilites handing and add SASL emitters

---

src/irc.ts
src/splitLines.ts
test/data/fixtures.json
test/test-irc.js

Supersedes #30
This basically is an implementation of ^ but written for the TS world.
Thanks to @xzfc for the initial PR.

Fix sending long messages - TS edition

---

src/irc.ts

Handle no-nick whois response

---

src/capabilities.ts

Some IRC servers (like ergo) send these in multiple lines (which we
accept according to our CAP request), and previously we would sometimes
incorrectly assume that we've already processed everything that matters,
resulting in (often intermittent) wrong assumptions about supported SASL
methods.

Support multiline CAP responses

---

changelog.d/84.bugfix
package.json
src/irc.ts
src/typings/utf-8-validate.d.ts

This appears to be the cause of https://github.com/matrix-org/matrix-appservice-irc/issues/1444

Call isValidUTF8 on a buffer object

---

CHANGELOG.md
changelog.d/84.bugfix
package-lock.json
package.json

Release 1.2.0

---

changelog.d/87.bug
src/parse_message.ts

It was not fine.
Reverts matrix-org/node-irc#87

Revert "Fix tokenization"

---

changelog.d/87.bug
src/parse_message.ts

Revert "Revert "Fix tokenization""

---

.github/CODEOWNERS
.github/pull_request_template.md
.github/workflows/changelog.yml
.github/workflows/sign-off.yml
.github/workflows/tests.yml
CONTRIBUTING.md
changelog.d/92.removal
package.json
scripts/changelog-check.sh

As documented in https://github.com/matrix-org/matrix-appservice-bridge/blob/develop/docs/platforms.md, we need to be on  Node 16 or greater.
I've also updated our CI to match our bridges too.

Update Node version & CI

---

changelog.d/104.misc
jest.config.js

5s wasn't leaving much time for it to be ready

Triple the integration test timeout

---

changelog.d/108.bugfix
spec/client.spec.ts
src/events.ts
src/irc.ts
src/testing/index.ts

Pretty straightforward bug. I've added testing to ensure we catch it.

Fix values in supported being duplicated
