lib/irc.js
package.json

Generate the correct list of channels where the user is in (for
commands: QUIT, NICK and KILL)

better way of finding what channels a user is in

---

package.json

Version 0.1.0 is incompatible with nodejs 4. Version 0.1.1 uses newer NaN APIs, supporting both old and new nodejs.

Don't pin node-icu-charset-detector

---

lib/irc.js

This adds a listener for when names are returned via /NAMES <channel>.
I've also fixed a bug where you can query the users in an empty room and get an error thrown.

Added names function

---

lib/irc.js
package.json

RFC 3484 specifies a client-side sorting order to apply to DNS results before making `connect()` attempts. Because of this sorting order, it turns out we always pick just one or two of Freenode's IPv6 candidates, instead of spreading the load uniformly and randomly among them.
This patch adds a boolean option, `bustRfc3484` that randomizes the DNS results before making the connection attempt, defeating this mechanism and allowing the connections to be spread more randomly around all the capable servers.

Initial hack at busting RFC 3484 sort order

---

lib/irc.js

Some IRC servers return less than 3 arguments with `319` reply.
This change prevents crash when working with these servers.

Fix parsing of code 319 (whoischannels) reply.

---

lib/irc.js

Verified using heap snapshots, this now means that `irc.Client` instances WILL be GCed provided there are no references to it in `matrix-appservice-irc`.

Fix a memory leak in the client to allow it to be GCed

---

lib/irc.js

Prior, if the connection timed out during a reconnect, the open socket would just sit idly forever.
Now, after 180 seconds (I don't know the "best" timeout interval, but the the Quassel IRC client uses a ping timeout of 180 seconds) of socket inactivity, a reconnect is attempted.
I have tested the code with my own bots and it works.
cf. [hubot-irc/issues#93](https://github.com/nandub/hubot-irc/issues/93)

Implement auto-connect upon socket timeout.

---

lib/irc.js

When reconnecting on timeout node-irc will create a new socket without properly destroying the old one. I have observed a race condition as a result of this that can hold multiple connections open at once. I can reliably reproduce this with [nandub/hubot-irc](https://github.com/nandub/hubot-irc). I can end up with as many open sockets as my retry limit.
Documentation for the destroy method [can be found here](https://nodejs.org/api/net.html#net_socket_destroy_exception).
I debated various other places to put this, but invoking it in connect() before allocating the connection seems like the safest place for all callers. This code is called from reconnect but could have other callers in the future.

Destroy existing socket before allocating a new one

---

README.md
docs/API.rst
lib/irc.js
package.json

This is needed to implement recoding support for the IRC bridge.

Add new option encoding_fallback to guess non-utf-8 encoding correctly.

---

lib/irc.js
package-lock.json
package.json

This seems to fix issues with CTCP actions containing ASCII control codes. 
On my test setup there is no more false re-encoding for utf-8 actions like with is-utf8 library.
I suggest a new release to npm after this to get the fix usable in Matrix IRC bridge. At least
IRCnet bridge suffers from the encoding bugs.

Replaced buggy is-utf8 with utf-8-validate library

---

example/externalSasl.js
lib/irc.js

I've been trying to get my matrix irc relay working on an amazon ec2 server. little did i know that freenode requires sasl auth from certain ip ranges, which include ec2, to prevent abuse. so I tried setting up plain sasl auth but i could not get it to work even after applying the patched described in https://github.com/matrix-org/matrix-appservice-irc/issues/689
I have however figured out that freenode will happily auth you if you use sasl EXTERNAL and attach a certificate to your conn
this PR simply adds a saslType option so you can set it to EXTERNAL if needed.

Add SASL EXTERNAL authentication and example

---

lib/irc.js

there won't always be a space after `sasl` in CAP ACK

---

lib/irc.js
package-lock.json
package.json
test/test-convert-encoding.js

This change will:
- Use more up to date node based libraries over the older native module ones (which also allows us to require those rather than making them optional)
- Update tests to use modernish JS
- Make the library require at least Node v12

Update character set based dependendencies

---

package.json
src/irc.ts

We always need to send a CAP END once we're finished negotiations capabilities. There were a few places where we didn't do this.

Send CAP END if not authenticating

---

src/irc.ts
test/data/fixtures.json

I noticed in matrix-org/matrix-appservice-irc#1353 that `irc.libera.chat` was rejecting connections from my bridge with `SASL access only`. After enabling `debug` for the IRC connection, I was able to see what commands were being sent to the server:
```
31 May 17:30:21 - Sending irc NICK/USER
31 May 17:30:21 - SEND: NICK melloc
31 May 17:30:21 - SEND: USER melloc 8 * @cody:timecube.club
31 May 17:30:21 - SEND: CAP LS 302
31 May 17:30:21 - GOT NOTICE from the server: "*** Notice -- You need to identify via SASL to use this server"
31 May 17:30:21 - Unhandled message: {
args: [ 'Closing Link: timecube.club (SASL access only)' ],
commandType: 'normal',
command: 'ERROR',
rawCommand: 'ERROR'
}
2021-05-31 17:30:21 ERROR:client-connection melloc@irc.libera.chat: {"args":["Closing Link: …
```

CAP LS should be sent before NICK and USER so that server knows we're going to attempt SASL authentication

---

src/irc.ts

Typical case of a mangled optional callback parameter

Fix provided QUIT message being ignored

---

src/codes.ts
src/irc.ts

Solanum (Libera) and other ircds send the 338 numeric
(RPL_WHOISACTUALLY) on some WHOIS replies, including your own. It's not
super useful but it does give the underlying IP address.
Signed-off-by: Emerson Veenstra <git@emersonveenstra.net>

Handle RPL_WHOISACTUALLY

---

changelog.d/75.bugfix
src/irc.ts

Don't emit registered on SASL replies, because the nick may not be
correct. Also always emit registered on RPL_WELCOME, because that
will only be sent after CAP END anyways. Fixes #74.
Signed off by Emerson Veenstra <git@emersonveenstra.net>

Fix when 'registered' is emitted

---

changelog.d/87.bug
src/parse_message.ts

Whitespaces other than the ASCII space are technically valid in a token;
and some servers (eg. some InspIRCd configs, as well as Hybrid) allow them
in channel names.
This means, for example, that the command
`KICK #channel\u00a0:test nickname :reason` was parsed as
`[command: "KICK", args: ["#channel", "test nickname :reason"]}`
instead of
`[command: "KICK", args: ["#channel\u00a0:test", "nickname", "reason"]}`

Fix tokenization

---

changelog.d/90.bugfix
src/irc.ts

if rejectUnauthorized is not disabled for `this.opt.certExpired = true`, the socket is already closed before the case on line 1201 can choose to keep the socket open anyways.

Disable rejectUnauthorized if expired certificates are allowed

---

.github/workflows/tests.yml
changelog.d/101.misc

Inspircd is a bit of a pain to modify the config of in GHA, and the defaults just ban our test rig outright. Ergo supports setting env flags so we can modify it if we need to.

Try using ergochat for CI testing

---

changelog.d/102.misc
package.json
spec/client.spec.ts
spec/external-connection.spec.ts
src/colors.ts
src/index.ts
src/parse_message.ts
src/testing/index.ts
src/typings/irc-colors.ts
yarn.lock

This ended up being *quite* the effort to get right. When implementing e2e testing in the IRC bridge we started depending on unexported bits of this lib to construct an e2e test rig, but ultimately it wasn't very safe and caused lots of issues. This PR attempts to export the useful parts of our test rig.
There are some notable changes to make this happen:
- I couldn't get irc-colours to play nice, so in the end I just took the bit of the 4 year old library that we cared about and ported it into the lib.
- We no longer use the slightly weird test construction pattern of `TestClass.describeTest` because it wasn't very developer friendly (obscured bits of Jest) and Jest **hated** being used to the point of crashing on import if it thought it was being used outside of a test env. This way is …

Improve and export integration testing rig

---

changelog.d/103.bugfix
src/irc.ts

- Object.entries(this.state.chans) is not working as it is a Map, it returns an empty array.
- message.nick in killChannel.users is not working as it is a Map too. Repacing with Map.prototype.has().
- Replacing delete killChannel.users[message.nick] with Map.prototype.delete().
- Doing the same with quitChannel.

Fix: this.state.chans and channel.users are Map type, not an Object type
